# Generated by Django 4.0.5 on 2022-06-27 23:03

import ProcessAdminRestApi.models.fields.PDF_field
import ProcessAdminRestApi.models.upload_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('method', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('is_calculated', ProcessAdminRestApi.models.upload_model.IsCalculatedField(default=False)),
                ('calculate', ProcessAdminRestApi.models.upload_model.CalculateField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period_date', models.DateField()),
                ('company_list', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HandelsregisterZIP',
            fields=[
                ('is_calculated', ProcessAdminRestApi.models.upload_model.IsCalculatedField(default=False)),
                ('calculate', ProcessAdminRestApi.models.upload_model.CalculateField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('handelsregister_zip', models.FileField(blank=True, null=True, upload_to='')),
                ('company_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.companylist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Handelsregisterauszug',
            fields=[
                ('is_calculated', ProcessAdminRestApi.models.upload_model.IsCalculatedField(default=False)),
                ('calculate', ProcessAdminRestApi.models.upload_model.CalculateField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField(default='')),
                ('handelsregister_auszug', ProcessAdminRestApi.models.fields.PDF_field.PDFField(blank=True, null=True, upload_to='')),
                ('company_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.companylist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
