# Generated by Django 4.0.5 on 2022-06-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0002_remove_handelsregisterzip_calculate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handelsregisterauszug',
            name='calculate',
        ),
        migrations.RemoveField(
            model_name='handelsregisterauszug',
            name='is_calculated',
        ),
    ]
