# Generated by Django 4.0.5 on 2022-07-16 22:33

import ProcessAdminRestApi.models.fields.XLSX_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0004_companylist_get_chronological_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vorname', models.TextField(default='')),
                ('nachname', models.TextField(default='')),
                ('ort', models.TextField(default='')),
                ('company_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.companylist')),
            ],
        ),
        migrations.AddField(
            model_name='handelsregisterzip',
            name='handelsregister_excel',
            field=ProcessAdminRestApi.models.fields.XLSX_field.XLSXField(blank=True, null=True, upload_to='excel'),
        ),
        migrations.CreateModel(
            name='Gesellschaft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bezeichnung', models.TextField(default='')),
                ('rechtsform', models.TextField(default='')),
                ('strasse', models.TextField(default='')),
                ('hausnummer', models.TextField(default='')),
                ('postleitzahl', models.TextField(default='')),
                ('ort', models.TextField(default='')),
                ('stammkapital', models.TextField(default='')),
                ('gegenstand_oder_geschaeftszweck', models.TextField(default='')),
                ('company_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.companylist')),
            ],
        ),
        migrations.CreateModel(
            name='Geschaeftsfuehrer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rollenbezeichnung', models.TextField(default='')),
                ('company_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.companylist')),
                ('geschaeftsfuehrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.executive')),
                ('gesellschaft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.gesellschaft')),
            ],
        ),
    ]
